"""PDF report generation service."""

import io
import os
from datetime import datetime

import matplotlib
matplotlib.use("Agg")
import matplotlib.pyplot as plt
import numpy as np


def generate_report_pdf(prediction: dict, explanation: dict, drug_name: str) -> bytes:
    """Generate a PDF clinical report with prediction results and SHAP analysis."""
    from matplotlib.backends.backend_pdf import PdfPages

    buf = io.BytesIO()

    with PdfPages(buf) as pdf:
        # Page 1: Verdict and summary
        fig, axes = plt.subplots(2, 1, figsize=(8.5, 11), gridspec_kw={"height_ratios": [1, 2]})

        # Header
        pred = prediction["predictions"][0]
        verdict = pred["verdict"]
        ln_ic50 = pred["ln_ic50"]
        confidence = pred["confidence"]

        verdict_color = "#2e7d32" if verdict == "Sensitive" else "#c62828"

        axes[0].set_xlim(0, 1)
        axes[0].set_ylim(0, 1)
        axes[0].axis("off")

        axes[0].text(0.5, 0.85, "PharmaAI Predictor", fontsize=20, fontweight="bold",
                     ha="center", va="center", color="#1a237e")
        axes[0].text(0.5, 0.7, "Drug Response Prediction Report", fontsize=14,
                     ha="center", va="center", color="#424242")
        axes[0].text(0.5, 0.5, f"Drug: {drug_name}", fontsize=12,
                     ha="center", va="center")
        axes[0].text(0.5, 0.35, f"Prediction: {verdict}", fontsize=16, fontweight="bold",
                     ha="center", va="center", color=verdict_color)
        axes[0].text(0.5, 0.2, f"LN_IC50: {ln_ic50:.4f}  |  Confidence: {confidence:.1%}",
                     fontsize=11, ha="center", va="center", color="#616161")
        axes[0].text(0.5, 0.05, f"Generated: {datetime.now().strftime('%Y-%m-%d %H:%M')}",
                     fontsize=9, ha="center", va="center", color="#9e9e9e")

        # SHAP bar chart
        top_genes = explanation.get("top_genes", [])
        if top_genes:
            names = [g["feature"] for g in reversed(top_genes)]
            values = [g["shap_value"] for g in reversed(top_genes)]
            colors = ["#2e7d32" if v < 0 else "#c62828" for v in values]

            axes[1].barh(names, values, color=colors, edgecolor="white", height=0.6)
            axes[1].set_xlabel("SHAP Value (impact on prediction)", fontsize=10)
            axes[1].set_title("Top Contributing Features", fontsize=13, fontweight="bold", pad=15)
            axes[1].axvline(x=0, color="black", linewidth=0.5)
            axes[1].tick_params(axis="y", labelsize=8)

            # Add legend
            from matplotlib.patches import Patch
            legend_elements = [
                Patch(facecolor="#2e7d32", label="Toward Sensitive (effective)"),
                Patch(facecolor="#c62828", label="Toward Resistant (ineffective)"),
            ]
            axes[1].legend(handles=legend_elements, loc="lower right", fontsize=8)
        else:
            axes[1].axis("off")
            axes[1].text(0.5, 0.5, "SHAP analysis not available", ha="center", va="center")

        plt.tight_layout()
        pdf.savefig(fig)
        plt.close(fig)

        # Page 2: Gene details table
        if top_genes:
            fig, ax = plt.subplots(figsize=(8.5, 11))
            ax.axis("off")

            ax.text(0.5, 0.97, "Feature Details", fontsize=16, fontweight="bold",
                    ha="center", va="top", transform=ax.transAxes)

            y = 0.92
            header = f"{'Rank':<6}{'Feature':<20}{'SHAP Value':<14}{'Direction':<20}{'Description'}"
            ax.text(0.02, y, header, fontsize=8, fontweight="bold", fontfamily="monospace",
                    transform=ax.transAxes)
            y -= 0.02
            ax.plot([0.02, 0.98], [y, y], color="black", linewidth=0.5,
                    transform=ax.transAxes, clip_on=False)
            y -= 0.01

            for gene in top_genes:
                direction_text = "Sensitive" if gene["direction"] == "toward_sensitive" else "Resistant"
                desc = gene.get("description", "")[:40]
                line = f"{gene['rank']:<6}{gene['feature']:<20}{gene['shap_value']:<14.6f}{direction_text:<20}{desc}"
                ax.text(0.02, y, line, fontsize=7, fontfamily="monospace",
                        transform=ax.transAxes)
                y -= 0.025

                if y < 0.05:
                    break

            # Footer
            ax.text(0.5, 0.02,
                    "This report is generated by an AI model and should be used as a clinical decision support tool only.\n"
                    "Always consult with qualified medical professionals before making treatment decisions.",
                    fontsize=7, ha="center", va="bottom", color="#9e9e9e", style="italic",
                    transform=ax.transAxes)

            plt.tight_layout()
            pdf.savefig(fig)
            plt.close(fig)

    buf.seek(0)
    return buf.read()
